// Industry Classification System for Campaign Finance Data
// Maps employer/organization names to industry categories

// Standard industry categories (based on OpenSecrets/CRP categories)
export const INDUSTRY_CATEGORIES = {
  // Finance & Business
  SECURITIES_INVESTMENT: 'Securities & Investment',
  BANKING: 'Banking',
  INSURANCE: 'Insurance',
  REAL_ESTATE: 'Real Estate',
  PRIVATE_EQUITY: 'Private Equity/Hedge Funds',
  ACCOUNTING: 'Accounting',

  // Professional Services
  LAWYERS_LAW_FIRMS: 'Lawyers/Law Firms',
  LOBBYISTS: 'Lobbyists',
  BUSINESS_SERVICES: 'Business Services',

  // Healthcare
  HEALTH_PROFESSIONALS: 'Health Professionals',
  HOSPITALS: 'Hospitals/Nursing Homes',
  PHARMACEUTICALS: 'Pharmaceuticals/Health Products',
  HEALTH_SERVICES: 'Health Services/HMOs',

  // Energy & Environment
  OIL_GAS: 'Oil & Gas',
  MINING: 'Mining',
  ELECTRIC_UTILITIES: 'Electric Utilities',
  ENVIRONMENTAL: 'Environmental Services',
  ALTERNATIVE_ENERGY: 'Alternative Energy',

  // Tech & Communications
  TECHNOLOGY: 'Electronics Mfg & Equip',
  INTERNET: 'Internet',
  TELECOM: 'Telecom Services & Equipment',
  TV_MOVIES_MUSIC: 'TV/Movies/Music',
  PRINTING_PUBLISHING: 'Printing & Publishing',

  // Manufacturing & Industry
  DEFENSE: 'Defense Aerospace',
  AUTOMOTIVE: 'Automotive',
  MANUFACTURING: 'Misc Manufacturing & Distributing',
  CONSTRUCTION: 'General Contractors',
  BUILDING_MATERIALS: 'Building Materials & Equipment',
  CHEMICAL: 'Chemical & Related Manufacturing',
  STEEL: 'Steel Production',
  TEXTILES: 'Textiles',

  // Transportation
  AIR_TRANSPORT: 'Air Transport',
  RAILROADS: 'Railroads',
  SEA_TRANSPORT: 'Sea Transport',
  TRUCKING: 'Trucking',
  AUTOMOTIVE_TRANSPORT: 'Automotive',

  // Agriculture & Food
  AGRICULTURE: 'Crop Production & Basic Processing',
  FOOD_PROCESSING: 'Food Processing & Sales',
  TOBACCO: 'Tobacco',
  FORESTRY: 'Forestry & Forest Products',

  // Labor & Unions
  LABOR_UNIONS: 'Labor Unions',
  PUBLIC_SECTOR_UNIONS: 'Public Sector Unions',
  TRANSPORTATION_UNIONS: 'Transportation Unions',
  BUILDING_TRADES: 'Building Trade Unions',
  INDUSTRIAL_UNIONS: 'Industrial Unions',

  // Government & Politics
  LEADERSHIP_PACS: 'Leadership PACs',
  DEMOCRATIC_PARTY: 'Democratic/Liberal',
  REPUBLICAN_PARTY: 'Republican/Conservative',
  PRO_ISRAEL: 'Pro-Israel',
  HUMAN_RIGHTS: 'Human Rights',
  ENVIRONMENT_GROUPS: 'Environment',
  GUN_RIGHTS: 'Gun Rights',
  GUN_CONTROL: 'Gun Control',
  WOMENS_ISSUES: "Women's Issues",

  // Education
  EDUCATION: 'Education',

  // Retail & Consumer
  RETAIL: 'Retail Sales',
  FOOD_BEVERAGE: 'Food & Beverage',
  LODGING_TOURISM: 'Lodging/Tourism',
  CASINOS_GAMBLING: 'Casinos/Gambling',
  RECREATION: 'Recreation/Live Entertainment',

  // Other
  RETIRED: 'Retired',
  HOMEMAKERS: 'Homemakers/Non-income earners',
  CIVIL_SERVANTS: 'Civil Servants/Public Officials',
  CLERGY: 'Clergy & Religious Organizations',
  MILITARY: 'Military',
  MISC_BUSINESS: 'Misc Business',
  NON_CONTRIBUTION: 'Non-contribution',
  UNKNOWN: 'Unknown/Other',
} as const;

export type IndustryCategory = typeof INDUSTRY_CATEGORIES[keyof typeof INDUSTRY_CATEGORIES];

// Static mapping of well-known organizations to industries
// This provides fast, accurate classification for major donors
export const EMPLOYER_TO_INDUSTRY: Record<string, IndustryCategory> = {
  // Major Investment Banks & Finance
  'GOLDMAN SACHS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'GOLDMAN SACHS GROUP': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'MORGAN STANLEY': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'JP MORGAN': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'JP MORGAN CHASE': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'JPMORGAN CHASE': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'JPMORGAN CHASE & CO': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'BANK OF AMERICA': INDUSTRY_CATEGORIES.BANKING,
  'CITIGROUP': INDUSTRY_CATEGORIES.BANKING,
  'CITI': INDUSTRY_CATEGORIES.BANKING,
  'CITIBANK': INDUSTRY_CATEGORIES.BANKING,
  'WELLS FARGO': INDUSTRY_CATEGORIES.BANKING,
  'CREDIT SUISSE': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'UBS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'DEUTSCHE BANK': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'BARCLAYS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'BLACKSTONE': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'BLACKSTONE GROUP': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'BLACKROCK': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'KKR': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'CARLYLE GROUP': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'APOLLO GLOBAL': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'CITADEL': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'BRIDGEWATER': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'TWO SIGMA': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'RENAISSANCE TECHNOLOGIES': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'ELLIOTT MANAGEMENT': INDUSTRY_CATEGORIES.PRIVATE_EQUITY,
  'FIDELITY': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'FIDELITY INVESTMENTS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'VANGUARD': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'CHARLES SCHWAB': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'TD AMERITRADE': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'RBC CAPITAL MARKETS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'RBC': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'JANE STREET': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'JANE STREET CAPITAL': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'SUSQUEHANNA': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'LAZARD': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'EVERCORE': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'MOELIS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'JEFFERIES': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'COWEN': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'PIPER SANDLER': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'WILLIAM BLAIR': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'STIFEL': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'RAYMOND JAMES': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'EDWARD JONES': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'AMERIPRISE': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,

  // Insurance
  'STATE FARM': INDUSTRY_CATEGORIES.INSURANCE,
  'ALLSTATE': INDUSTRY_CATEGORIES.INSURANCE,
  'PROGRESSIVE': INDUSTRY_CATEGORIES.INSURANCE,
  'GEICO': INDUSTRY_CATEGORIES.INSURANCE,
  'LIBERTY MUTUAL': INDUSTRY_CATEGORIES.INSURANCE,
  'TRAVELERS': INDUSTRY_CATEGORIES.INSURANCE,
  'CHUBB': INDUSTRY_CATEGORIES.INSURANCE,
  'CHUBB GROUP OF INSURANCE COMPANIES': INDUSTRY_CATEGORIES.INSURANCE,
  'AIG': INDUSTRY_CATEGORIES.INSURANCE,
  'METLIFE': INDUSTRY_CATEGORIES.INSURANCE,
  'PRUDENTIAL': INDUSTRY_CATEGORIES.INSURANCE,
  'AETNA': INDUSTRY_CATEGORIES.INSURANCE,
  'CIGNA': INDUSTRY_CATEGORIES.INSURANCE,
  'HUMANA': INDUSTRY_CATEGORIES.INSURANCE,
  'UNITED HEALTH': INDUSTRY_CATEGORIES.INSURANCE,
  'UNITEDHEALTH': INDUSTRY_CATEGORIES.INSURANCE,
  'UNITEDHEALTH GROUP': INDUSTRY_CATEGORIES.INSURANCE,
  'ANTHEM': INDUSTRY_CATEGORIES.INSURANCE,
  'BLUE CROSS': INDUSTRY_CATEGORIES.INSURANCE,
  'BLUE SHIELD': INDUSTRY_CATEGORIES.INSURANCE,
  'KAISER': INDUSTRY_CATEGORIES.HEALTH_SERVICES,
  'KAISER PERMANENTE': INDUSTRY_CATEGORIES.HEALTH_SERVICES,

  // Real Estate
  'CBRE': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'JLL': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'JONES LANG LASALLE': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'CUSHMAN WAKEFIELD': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'MARCUS MILLICHAP': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'COLDWELL BANKER': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'CENTURY 21': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'KELLER WILLIAMS': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'RE/MAX': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'COMPASS': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'ZILLOW': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'REDFIN': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'BROOKFIELD': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'RELATED COMPANIES': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'SIMON PROPERTY': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'PROLOGIS': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'EQUINIX': INDUSTRY_CATEGORIES.REAL_ESTATE,
  'DIGITAL REALTY': INDUSTRY_CATEGORIES.REAL_ESTATE,

  // Technology
  'GOOGLE': INDUSTRY_CATEGORIES.INTERNET,
  'ALPHABET': INDUSTRY_CATEGORIES.INTERNET,
  'MICROSOFT': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'APPLE': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'META': INDUSTRY_CATEGORIES.INTERNET,
  'FACEBOOK': INDUSTRY_CATEGORIES.INTERNET,
  'AMAZON': INDUSTRY_CATEGORIES.INTERNET,
  'NETFLIX': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'TWITTER': INDUSTRY_CATEGORIES.INTERNET,
  'X CORP': INDUSTRY_CATEGORIES.INTERNET,
  'ORACLE': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'SALESFORCE': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'ADOBE': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'IBM': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'INTEL': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'NVIDIA': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'AMD': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'QUALCOMM': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'BROADCOM': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'CISCO': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'DELL': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'HP': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'HEWLETT PACKARD': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'SAP': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'VMWARE': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'PALANTIR': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'SNOWFLAKE': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'DATADOG': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'CROWDSTRIKE': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'SERVICENOW': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'WORKDAY': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'INTUIT': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'AUTODESK': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'UBER': INDUSTRY_CATEGORIES.INTERNET,
  'LYFT': INDUSTRY_CATEGORIES.INTERNET,
  'AIRBNB': INDUSTRY_CATEGORIES.INTERNET,
  'DOORDASH': INDUSTRY_CATEGORIES.INTERNET,
  'STRIPE': INDUSTRY_CATEGORIES.INTERNET,
  'SQUARE': INDUSTRY_CATEGORIES.INTERNET,
  'BLOCK': INDUSTRY_CATEGORIES.INTERNET,
  'PAYPAL': INDUSTRY_CATEGORIES.INTERNET,
  'SHOPIFY': INDUSTRY_CATEGORIES.INTERNET,
  'LINKEDIN': INDUSTRY_CATEGORIES.INTERNET,
  'SNAP': INDUSTRY_CATEGORIES.INTERNET,
  'SNAPCHAT': INDUSTRY_CATEGORIES.INTERNET,
  'PINTEREST': INDUSTRY_CATEGORIES.INTERNET,
  'REDDIT': INDUSTRY_CATEGORIES.INTERNET,
  'TIKTOK': INDUSTRY_CATEGORIES.INTERNET,
  'BYTEDANCE': INDUSTRY_CATEGORIES.INTERNET,
  'OPENAI': INDUSTRY_CATEGORIES.TECHNOLOGY,
  'ANTHROPIC': INDUSTRY_CATEGORIES.TECHNOLOGY,

  // Telecom
  'AT&T': INDUSTRY_CATEGORIES.TELECOM,
  'VERIZON': INDUSTRY_CATEGORIES.TELECOM,
  'T-MOBILE': INDUSTRY_CATEGORIES.TELECOM,
  'SPRINT': INDUSTRY_CATEGORIES.TELECOM,
  'COMCAST': INDUSTRY_CATEGORIES.TELECOM,
  'CHARTER': INDUSTRY_CATEGORIES.TELECOM,
  'COX': INDUSTRY_CATEGORIES.TELECOM,
  'DISH': INDUSTRY_CATEGORIES.TELECOM,

  // Media & Entertainment
  'DISNEY': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'WALT DISNEY': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'WARNER BROS': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'WARNER MEDIA': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'PARAMOUNT': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'SONY': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'NBCUNIVERSAL': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'NBC': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'CBS': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'ABC': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'FOX': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'NEWS CORP': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'LIVE NATION': INDUSTRY_CATEGORIES.RECREATION,
  'AEG': INDUSTRY_CATEGORIES.RECREATION,
  'SPOTIFY': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'UNIVERSAL MUSIC': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'WARNER MUSIC': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,
  'SONY MUSIC': INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC,

  // Energy
  'EXXON': INDUSTRY_CATEGORIES.OIL_GAS,
  'EXXONMOBIL': INDUSTRY_CATEGORIES.OIL_GAS,
  'CHEVRON': INDUSTRY_CATEGORIES.OIL_GAS,
  'BP': INDUSTRY_CATEGORIES.OIL_GAS,
  'SHELL': INDUSTRY_CATEGORIES.OIL_GAS,
  'CONOCOPHILLIPS': INDUSTRY_CATEGORIES.OIL_GAS,
  'MARATHON': INDUSTRY_CATEGORIES.OIL_GAS,
  'VALERO': INDUSTRY_CATEGORIES.OIL_GAS,
  'PHILLIPS 66': INDUSTRY_CATEGORIES.OIL_GAS,
  'OCCIDENTAL': INDUSTRY_CATEGORIES.OIL_GAS,
  'HESS': INDUSTRY_CATEGORIES.OIL_GAS,
  'DEVON': INDUSTRY_CATEGORIES.OIL_GAS,
  'PIONEER': INDUSTRY_CATEGORIES.OIL_GAS,
  'EOG': INDUSTRY_CATEGORIES.OIL_GAS,
  'HALLIBURTON': INDUSTRY_CATEGORIES.OIL_GAS,
  'SCHLUMBERGER': INDUSTRY_CATEGORIES.OIL_GAS,
  'BAKER HUGHES': INDUSTRY_CATEGORIES.OIL_GAS,
  'DUKE ENERGY': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'SOUTHERN COMPANY': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'DOMINION': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'NEXTERA': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'EXELON': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'AES': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'PG&E': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'EDISON': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'CONSTELLATION': INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES,
  'TESLA': INDUSTRY_CATEGORIES.ALTERNATIVE_ENERGY,
  'FIRST SOLAR': INDUSTRY_CATEGORIES.ALTERNATIVE_ENERGY,
  'SUNRUN': INDUSTRY_CATEGORIES.ALTERNATIVE_ENERGY,

  // Law Firms
  'SKADDEN': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'SKADDEN ARPS': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'KIRKLAND': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'KIRKLAND & ELLIS': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'LATHAM': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'LATHAM & WATKINS': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'SULLIVAN & CROMWELL': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'WACHTELL': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'CRAVATH': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'DAVIS POLK': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'SIMPSON THACHER': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'PAUL WEISS': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'CLEARY GOTTLIEB': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'GIBSON DUNN': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'SIDLEY': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'SIDLEY AUSTIN': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'JONES DAY': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'BAKER MCKENZIE': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'DLA PIPER': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'MORGAN LEWIS': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'WHITE & CASE': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'HOGAN LOVELLS': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'WILMER': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'WILMERHALE': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'COVINGTON': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'COVINGTON & BURLING': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'AKIN GUMP': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'GREENBERG TRAURIG': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'QUINN EMANUEL': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'WEIL': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'WEIL GOTSHAL': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'PROSKAUER': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'ROPES & GRAY': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'GOODWIN': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'ORRICK': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'MAYER BROWN': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'KING & SPALDING': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'PERKINS COIE': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'ARNOLD & PORTER': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'DEBEVOISE': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'MILBANK': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'MORRISON FOERSTER': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'SHEARMAN': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,
  'WILLKIE': INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS,

  // Accounting
  'DELOITTE': INDUSTRY_CATEGORIES.ACCOUNTING,
  'PWC': INDUSTRY_CATEGORIES.ACCOUNTING,
  'PRICEWATERHOUSECOOPERS': INDUSTRY_CATEGORIES.ACCOUNTING,
  'EY': INDUSTRY_CATEGORIES.ACCOUNTING,
  'ERNST & YOUNG': INDUSTRY_CATEGORIES.ACCOUNTING,
  'KPMG': INDUSTRY_CATEGORIES.ACCOUNTING,
  'BDO': INDUSTRY_CATEGORIES.ACCOUNTING,
  'RSM': INDUSTRY_CATEGORIES.ACCOUNTING,
  'GRANT THORNTON': INDUSTRY_CATEGORIES.ACCOUNTING,
  'CROWE': INDUSTRY_CATEGORIES.ACCOUNTING,

  // Pharmaceuticals
  'PFIZER': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'JOHNSON & JOHNSON': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'MERCK': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'ABBVIE': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'BRISTOL MYERS': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'BRISTOL-MYERS SQUIBB': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'ELI LILLY': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'AMGEN': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'GILEAD': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'REGENERON': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'MODERNA': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'NOVARTIS': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'ROCHE': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'SANOFI': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'ASTRAZENECA': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'GSK': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'GLAXOSMITHKLINE': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'BAYER': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'BIOGEN': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'VERTEX': INDUSTRY_CATEGORIES.PHARMACEUTICALS,
  'CVS': INDUSTRY_CATEGORIES.HEALTH_SERVICES,
  'CVS HEALTH': INDUSTRY_CATEGORIES.HEALTH_SERVICES,
  'WALGREENS': INDUSTRY_CATEGORIES.HEALTH_SERVICES,
  'RITE AID': INDUSTRY_CATEGORIES.HEALTH_SERVICES,

  // Hospitals & Healthcare
  'HCA': INDUSTRY_CATEGORIES.HOSPITALS,
  'HCA HEALTHCARE': INDUSTRY_CATEGORIES.HOSPITALS,
  'TENET': INDUSTRY_CATEGORIES.HOSPITALS,
  'COMMUNITY HEALTH': INDUSTRY_CATEGORIES.HOSPITALS,
  'UNIVERSAL HEALTH': INDUSTRY_CATEGORIES.HOSPITALS,
  'MAYO CLINIC': INDUSTRY_CATEGORIES.HOSPITALS,
  'CLEVELAND CLINIC': INDUSTRY_CATEGORIES.HOSPITALS,
  'JOHNS HOPKINS': INDUSTRY_CATEGORIES.HOSPITALS,
  'MOUNT SINAI': INDUSTRY_CATEGORIES.HOSPITALS,
  'NYU LANGONE': INDUSTRY_CATEGORIES.HOSPITALS,
  'MASS GENERAL': INDUSTRY_CATEGORIES.HOSPITALS,
  'UCLA HEALTH': INDUSTRY_CATEGORIES.HOSPITALS,
  'CEDARS SINAI': INDUSTRY_CATEGORIES.HOSPITALS,

  // Defense
  'LOCKHEED': INDUSTRY_CATEGORIES.DEFENSE,
  'LOCKHEED MARTIN': INDUSTRY_CATEGORIES.DEFENSE,
  'BOEING': INDUSTRY_CATEGORIES.DEFENSE,
  'RAYTHEON': INDUSTRY_CATEGORIES.DEFENSE,
  'RTX': INDUSTRY_CATEGORIES.DEFENSE,
  'NORTHROP': INDUSTRY_CATEGORIES.DEFENSE,
  'NORTHROP GRUMMAN': INDUSTRY_CATEGORIES.DEFENSE,
  'GENERAL DYNAMICS': INDUSTRY_CATEGORIES.DEFENSE,
  'L3HARRIS': INDUSTRY_CATEGORIES.DEFENSE,
  'BAE SYSTEMS': INDUSTRY_CATEGORIES.DEFENSE,
  'LEIDOS': INDUSTRY_CATEGORIES.DEFENSE,
  'SAIC': INDUSTRY_CATEGORIES.DEFENSE,
  'BOOZ ALLEN': INDUSTRY_CATEGORIES.DEFENSE,

  // Automotive
  'FORD': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'GM': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'GENERAL MOTORS': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'STELLANTIS': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'CHRYSLER': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'TOYOTA': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'HONDA': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'NISSAN': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'BMW': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'MERCEDES': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'VOLKSWAGEN': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'RIVIAN': INDUSTRY_CATEGORIES.AUTOMOTIVE,
  'LUCID': INDUSTRY_CATEGORIES.AUTOMOTIVE,

  // Airlines
  'DELTA': INDUSTRY_CATEGORIES.AIR_TRANSPORT,
  'DELTA AIR LINES': INDUSTRY_CATEGORIES.AIR_TRANSPORT,
  'UNITED': INDUSTRY_CATEGORIES.AIR_TRANSPORT,
  'UNITED AIRLINES': INDUSTRY_CATEGORIES.AIR_TRANSPORT,
  'AMERICAN AIRLINES': INDUSTRY_CATEGORIES.AIR_TRANSPORT,
  'SOUTHWEST': INDUSTRY_CATEGORIES.AIR_TRANSPORT,
  'JETBLUE': INDUSTRY_CATEGORIES.AIR_TRANSPORT,
  'ALASKA AIRLINES': INDUSTRY_CATEGORIES.AIR_TRANSPORT,

  // Retail
  'WALMART': INDUSTRY_CATEGORIES.RETAIL,
  'TARGET': INDUSTRY_CATEGORIES.RETAIL,
  'COSTCO': INDUSTRY_CATEGORIES.RETAIL,
  'HOME DEPOT': INDUSTRY_CATEGORIES.RETAIL,
  'LOWES': INDUSTRY_CATEGORIES.RETAIL,
  "LOWE'S": INDUSTRY_CATEGORIES.RETAIL,
  'BEST BUY': INDUSTRY_CATEGORIES.RETAIL,
  'KROGER': INDUSTRY_CATEGORIES.RETAIL,
  'PUBLIX': INDUSTRY_CATEGORIES.RETAIL,
  'ALBERTSONS': INDUSTRY_CATEGORIES.RETAIL,
  'SAFEWAY': INDUSTRY_CATEGORIES.RETAIL,
  'WHOLE FOODS': INDUSTRY_CATEGORIES.RETAIL,
  'NORDSTROM': INDUSTRY_CATEGORIES.RETAIL,
  "MACY'S": INDUSTRY_CATEGORIES.RETAIL,
  'MACYS': INDUSTRY_CATEGORIES.RETAIL,
  'TJX': INDUSTRY_CATEGORIES.RETAIL,
  'ROSS': INDUSTRY_CATEGORIES.RETAIL,
  'GAP': INDUSTRY_CATEGORIES.RETAIL,
  'NIKE': INDUSTRY_CATEGORIES.RETAIL,

  // Food & Beverage
  'COCA COLA': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'PEPSI': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'PEPSICO': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'NESTLE': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'KRAFT': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'KRAFT HEINZ': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'GENERAL MILLS': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'KELLOGG': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  "KELLOGG'S": INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'MONDELEZ': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'TYSON': INDUSTRY_CATEGORIES.FOOD_PROCESSING,
  'CARGILL': INDUSTRY_CATEGORIES.FOOD_PROCESSING,
  'ADM': INDUSTRY_CATEGORIES.FOOD_PROCESSING,
  'ARCHER DANIELS': INDUSTRY_CATEGORIES.FOOD_PROCESSING,
  'MCDONALD': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  "MCDONALD'S": INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'STARBUCKS': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'CHIPOTLE': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'YUM BRANDS': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,
  'DARDEN': INDUSTRY_CATEGORIES.FOOD_BEVERAGE,

  // Unions & Labor
  'AFL-CIO': INDUSTRY_CATEGORIES.LABOR_UNIONS,
  'SEIU': INDUSTRY_CATEGORIES.PUBLIC_SECTOR_UNIONS,
  'AFSCME': INDUSTRY_CATEGORIES.PUBLIC_SECTOR_UNIONS,
  'AFT': INDUSTRY_CATEGORIES.PUBLIC_SECTOR_UNIONS,
  'NEA': INDUSTRY_CATEGORIES.PUBLIC_SECTOR_UNIONS,
  'TEAMSTERS': INDUSTRY_CATEGORIES.TRANSPORTATION_UNIONS,
  'UAW': INDUSTRY_CATEGORIES.INDUSTRIAL_UNIONS,
  'USW': INDUSTRY_CATEGORIES.INDUSTRIAL_UNIONS,
  'IBEW': INDUSTRY_CATEGORIES.BUILDING_TRADES,
  'LIUNA': INDUSTRY_CATEGORIES.BUILDING_TRADES,
  'UNITE HERE': INDUSTRY_CATEGORIES.LABOR_UNIONS,
  'CWA': INDUSTRY_CATEGORIES.LABOR_UNIONS,
  'UFCW': INDUSTRY_CATEGORIES.LABOR_UNIONS,
  'IAFF': INDUSTRY_CATEGORIES.PUBLIC_SECTOR_UNIONS,
  'IUOE': INDUSTRY_CATEGORIES.BUILDING_TRADES,

  // PACs & Political Organizations
  'NO LABELS': INDUSTRY_CATEGORIES.LEADERSHIP_PACS,
  'NO LABELS PROBLEM SOLVERS': INDUSTRY_CATEGORIES.LEADERSHIP_PACS,
  'AIPAC': INDUSTRY_CATEGORIES.PRO_ISRAEL,
  'AMERICAN ISRAEL PUBLIC AFFAIRS': INDUSTRY_CATEGORIES.PRO_ISRAEL,
  'REPUBLICAN JEWISH COALITION': INDUSTRY_CATEGORIES.PRO_ISRAEL,
  'RATIONALWAVE CAPITAL': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'RATIONALWAVE CAPITAL PARTNERS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'BET INVESTMENTS': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'BLUFF POINT': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'BLUFF POINT ASSOC': INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT,
  'STARKEY': INDUSTRY_CATEGORIES.HEALTH_PROFESSIONALS,
  'STARKEY HEARING': INDUSTRY_CATEGORIES.HEALTH_PROFESSIONALS,
  'STARKEY HEARING TECHNOLOGIES': INDUSTRY_CATEGORIES.HEALTH_PROFESSIONALS,

  // Education
  'HARVARD': INDUSTRY_CATEGORIES.EDUCATION,
  'YALE': INDUSTRY_CATEGORIES.EDUCATION,
  'PRINCETON': INDUSTRY_CATEGORIES.EDUCATION,
  'STANFORD': INDUSTRY_CATEGORIES.EDUCATION,
  'MIT': INDUSTRY_CATEGORIES.EDUCATION,
  'COLUMBIA': INDUSTRY_CATEGORIES.EDUCATION,
  'UNIVERSITY OF': INDUSTRY_CATEGORIES.EDUCATION,

  // Hotels & Lodging
  'MARRIOTT': INDUSTRY_CATEGORIES.LODGING_TOURISM,
  'HILTON': INDUSTRY_CATEGORIES.LODGING_TOURISM,
  'HYATT': INDUSTRY_CATEGORIES.LODGING_TOURISM,
  'IHG': INDUSTRY_CATEGORIES.LODGING_TOURISM,
  'WYNDHAM': INDUSTRY_CATEGORIES.LODGING_TOURISM,
  'MGM': INDUSTRY_CATEGORIES.CASINOS_GAMBLING,
  'CAESARS': INDUSTRY_CATEGORIES.CASINOS_GAMBLING,
  'LAS VEGAS SANDS': INDUSTRY_CATEGORIES.CASINOS_GAMBLING,
  'WYNN': INDUSTRY_CATEGORIES.CASINOS_GAMBLING,

  // Construction
  'BECHTEL': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'FLUOR': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'JACOBS': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'AECOM': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'TURNER': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'SKANSKA': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'MORTENSON': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'CLARK': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'KIEWIT': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'LENNAR': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'DR HORTON': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'PULTE': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'TOLL BROTHERS': INDUSTRY_CATEGORIES.CONSTRUCTION,
  'KB HOME': INDUSTRY_CATEGORIES.CONSTRUCTION,

  // Shipping & Logistics
  'FEDEX': INDUSTRY_CATEGORIES.TRUCKING,
  'UPS': INDUSTRY_CATEGORIES.TRUCKING,
  'DHL': INDUSTRY_CATEGORIES.TRUCKING,
  'XPO': INDUSTRY_CATEGORIES.TRUCKING,
  'JB HUNT': INDUSTRY_CATEGORIES.TRUCKING,
  'OLD DOMINION': INDUSTRY_CATEGORIES.TRUCKING,
  'SCHNEIDER': INDUSTRY_CATEGORIES.TRUCKING,

  // Special Categories
  'SELF-EMPLOYED': INDUSTRY_CATEGORIES.MISC_BUSINESS,
  'SELF EMPLOYED': INDUSTRY_CATEGORIES.MISC_BUSINESS,
  'RETIRED': INDUSTRY_CATEGORIES.RETIRED,
  'NOT EMPLOYED': INDUSTRY_CATEGORIES.HOMEMAKERS,
  'HOMEMAKER': INDUSTRY_CATEGORIES.HOMEMAKERS,
  'NONE': INDUSTRY_CATEGORIES.NON_CONTRIBUTION,
  'N/A': INDUSTRY_CATEGORIES.UNKNOWN,
  'INFORMATION REQUESTED': INDUSTRY_CATEGORIES.UNKNOWN,
};

// Keyword-based classification for fuzzy matching
export const INDUSTRY_KEYWORDS: Array<{ keywords: string[], industry: IndustryCategory }> = [
  // Finance
  { keywords: ['INVESTMENT', 'CAPITAL', 'ASSET MANAGEMENT', 'HEDGE FUND', 'VENTURE', 'PARTNERS LP', 'FUND'], industry: INDUSTRY_CATEGORIES.SECURITIES_INVESTMENT },
  { keywords: ['BANK', 'BANKING', 'FINANCIAL', 'CREDIT UNION'], industry: INDUSTRY_CATEGORIES.BANKING },
  { keywords: ['INSURANCE', 'MUTUAL', 'UNDERWRITER'], industry: INDUSTRY_CATEGORIES.INSURANCE },
  { keywords: ['REAL ESTATE', 'REALTY', 'PROPERTIES', 'PROPERTY', 'MORTGAGE', 'REIT'], industry: INDUSTRY_CATEGORIES.REAL_ESTATE },
  { keywords: ['PRIVATE EQUITY', 'PE FUND', 'BUYOUT'], industry: INDUSTRY_CATEGORIES.PRIVATE_EQUITY },

  // Professional Services
  { keywords: ['LAW FIRM', 'LAW OFFICE', 'ATTORNEY', 'LEGAL', 'LLP', 'PLLC'], industry: INDUSTRY_CATEGORIES.LAWYERS_LAW_FIRMS },
  { keywords: ['LOBBYING', 'GOVERNMENT RELATIONS', 'PUBLIC AFFAIRS', 'ADVOCACY'], industry: INDUSTRY_CATEGORIES.LOBBYISTS },
  { keywords: ['ACCOUNTING', 'CPA', 'TAX', 'AUDIT'], industry: INDUSTRY_CATEGORIES.ACCOUNTING },
  { keywords: ['CONSULTING', 'ADVISORS', 'ADVISORY', 'MANAGEMENT CONSULTING'], industry: INDUSTRY_CATEGORIES.BUSINESS_SERVICES },

  // Healthcare
  { keywords: ['HOSPITAL', 'MEDICAL CENTER', 'HEALTH SYSTEM', 'CLINIC', 'HEALTHCARE'], industry: INDUSTRY_CATEGORIES.HOSPITALS },
  { keywords: ['PHARMA', 'PHARMACEUTICAL', 'BIOTECH', 'THERAPEUTICS', 'BIOSCIENCES'], industry: INDUSTRY_CATEGORIES.PHARMACEUTICALS },
  { keywords: ['PHYSICIAN', 'DOCTOR', 'MD', 'SURGEON', 'DENTIST', 'DENTAL', 'OPTOMETRY', 'CHIROPRACT'], industry: INDUSTRY_CATEGORIES.HEALTH_PROFESSIONALS },

  // Technology
  { keywords: ['TECHNOLOGY', 'TECH', 'SOFTWARE', 'COMPUTING', 'IT SERVICES', 'SYSTEMS'], industry: INDUSTRY_CATEGORIES.TECHNOLOGY },
  { keywords: ['INTERNET', 'ONLINE', 'DIGITAL', 'E-COMMERCE', 'ECOMMERCE', 'WEB', 'APP'], industry: INDUSTRY_CATEGORIES.INTERNET },
  { keywords: ['TELECOM', 'WIRELESS', 'COMMUNICATIONS', 'CABLE', 'SATELLITE'], industry: INDUSTRY_CATEGORIES.TELECOM },

  // Energy
  { keywords: ['OIL', 'GAS', 'PETROLEUM', 'ENERGY', 'EXPLORATION', 'DRILLING', 'PIPELINE'], industry: INDUSTRY_CATEGORIES.OIL_GAS },
  { keywords: ['ELECTRIC', 'UTILITY', 'POWER', 'GRID'], industry: INDUSTRY_CATEGORIES.ELECTRIC_UTILITIES },
  { keywords: ['SOLAR', 'WIND', 'RENEWABLE', 'CLEAN ENERGY', 'GREEN'], industry: INDUSTRY_CATEGORIES.ALTERNATIVE_ENERGY },
  { keywords: ['MINING', 'COAL', 'MINERAL'], industry: INDUSTRY_CATEGORIES.MINING },

  // Manufacturing & Defense
  { keywords: ['DEFENSE', 'AEROSPACE', 'MILITARY', 'WEAPONS'], industry: INDUSTRY_CATEGORIES.DEFENSE },
  { keywords: ['AUTOMOTIVE', 'AUTO', 'CAR', 'VEHICLE', 'MOTOR'], industry: INDUSTRY_CATEGORIES.AUTOMOTIVE },
  { keywords: ['MANUFACTURING', 'FACTORY', 'INDUSTRIAL', 'MACHINERY'], industry: INDUSTRY_CATEGORIES.MANUFACTURING },
  { keywords: ['CONSTRUCTION', 'BUILDER', 'CONTRACTOR', 'DEVELOPMENT'], industry: INDUSTRY_CATEGORIES.CONSTRUCTION },
  { keywords: ['CHEMICAL', 'PLASTICS', 'POLYMER'], industry: INDUSTRY_CATEGORIES.CHEMICAL },

  // Transportation
  { keywords: ['AIRLINE', 'AVIATION', 'AIR TRANSPORT', 'AIRCRAFT'], industry: INDUSTRY_CATEGORIES.AIR_TRANSPORT },
  { keywords: ['RAILROAD', 'RAIL', 'TRAIN'], industry: INDUSTRY_CATEGORIES.RAILROADS },
  { keywords: ['SHIPPING', 'MARITIME', 'SHIP', 'PORT'], industry: INDUSTRY_CATEGORIES.SEA_TRANSPORT },
  { keywords: ['TRUCKING', 'FREIGHT', 'LOGISTICS', 'TRANSPORTATION'], industry: INDUSTRY_CATEGORIES.TRUCKING },

  // Consumer & Retail
  { keywords: ['RETAIL', 'STORE', 'SHOP', 'MALL'], industry: INDUSTRY_CATEGORIES.RETAIL },
  { keywords: ['RESTAURANT', 'FOOD SERVICE', 'CATERING', 'DINING'], industry: INDUSTRY_CATEGORIES.FOOD_BEVERAGE },
  { keywords: ['HOTEL', 'RESORT', 'HOSPITALITY', 'LODGING'], industry: INDUSTRY_CATEGORIES.LODGING_TOURISM },
  { keywords: ['CASINO', 'GAMING', 'GAMBLING'], industry: INDUSTRY_CATEGORIES.CASINOS_GAMBLING },

  // Media & Entertainment
  { keywords: ['MEDIA', 'BROADCASTING', 'TELEVISION', 'RADIO', 'NEWS', 'FILM', 'MOVIE', 'STUDIO', 'ENTERTAINMENT', 'MUSIC', 'RECORDING'], industry: INDUSTRY_CATEGORIES.TV_MOVIES_MUSIC },
  { keywords: ['PUBLISHING', 'NEWSPAPER', 'MAGAZINE', 'PRINT'], industry: INDUSTRY_CATEGORIES.PRINTING_PUBLISHING },

  // Agriculture & Food
  { keywords: ['FARM', 'AGRICULTURE', 'CROP', 'GRAIN', 'LIVESTOCK', 'DAIRY'], industry: INDUSTRY_CATEGORIES.AGRICULTURE },
  { keywords: ['FOOD PROCESSING', 'BEVERAGE', 'MEAT', 'POULTRY'], industry: INDUSTRY_CATEGORIES.FOOD_PROCESSING },

  // Education
  { keywords: ['UNIVERSITY', 'COLLEGE', 'SCHOOL', 'EDUCATION', 'ACADEMIC'], industry: INDUSTRY_CATEGORIES.EDUCATION },

  // Unions
  { keywords: ['UNION', 'LABOR', 'AFL', 'CIO', 'WORKERS', 'BROTHERHOOD', 'SISTERHOOD'], industry: INDUSTRY_CATEGORIES.LABOR_UNIONS },

  // Political
  { keywords: ['PAC', 'POLITICAL', 'CAMPAIGN', 'COMMITTEE'], industry: INDUSTRY_CATEGORIES.LEADERSHIP_PACS },
  { keywords: ['ISRAEL', 'JEWISH', 'ZIONIST'], industry: INDUSTRY_CATEGORIES.PRO_ISRAEL },
];

/**
 * Classify an employer/organization name into an industry category
 * Uses static mapping first, then keyword matching
 */
export function classifyEmployer(employerName: string): IndustryCategory {
  if (!employerName) {
    return INDUSTRY_CATEGORIES.UNKNOWN;
  }

  const normalizedName = employerName.toUpperCase().trim();

  // Check static mapping first (exact or partial match)
  for (const [key, industry] of Object.entries(EMPLOYER_TO_INDUSTRY)) {
    if (normalizedName === key || normalizedName.includes(key) || key.includes(normalizedName)) {
      return industry;
    }
  }

  // Check keyword-based classification
  for (const { keywords, industry } of INDUSTRY_KEYWORDS) {
    for (const keyword of keywords) {
      if (normalizedName.includes(keyword)) {
        return industry;
      }
    }
  }

  // Check for occupation-based patterns
  if (normalizedName.includes('RETIRED') || normalizedName === 'RETIRED') {
    return INDUSTRY_CATEGORIES.RETIRED;
  }
  if (normalizedName.includes('SELF') || normalizedName.includes('SELF-EMPLOYED') || normalizedName.includes('OWNER')) {
    return INDUSTRY_CATEGORIES.MISC_BUSINESS;
  }
  if (normalizedName.includes('HOMEMAKER') || normalizedName.includes('NOT EMPLOYED') || normalizedName.includes('UNEMPLOYED')) {
    return INDUSTRY_CATEGORIES.HOMEMAKERS;
  }

  return INDUSTRY_CATEGORIES.UNKNOWN;
}

/**
 * Aggregate contributions by industry
 */
export interface IndustryContribution {
  industry: IndustryCategory;
  total: number;
  count: number;
  employers: string[];
}

export function aggregateByIndustry(
  contributions: Array<{ employer: string; total: number; count: number }>
): IndustryContribution[] {
  const industryMap = new Map<IndustryCategory, IndustryContribution>();

  for (const contrib of contributions) {
    const industry = classifyEmployer(contrib.employer);

    if (!industryMap.has(industry)) {
      industryMap.set(industry, {
        industry,
        total: 0,
        count: 0,
        employers: [],
      });
    }

    const entry = industryMap.get(industry)!;
    entry.total += contrib.total;
    entry.count += contrib.count;
    if (!entry.employers.includes(contrib.employer)) {
      entry.employers.push(contrib.employer);
    }
  }

  // Sort by total contribution amount descending
  return Array.from(industryMap.values())
    .sort((a, b) => b.total - a.total);
}
